# Generated by Django 2.2 on 2019-12-17 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author_first_name', models.CharField(blank=True, max_length=150)),
                ('author_second_name', models.CharField(blank=True, max_length=150)),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genres.Genre')),
            ],
        ),
    ]
